#!/usr/bin/env bash
# OX-ALPHA live credentials setup (one time, prompted).
#
# Writes ~/.ox_secrets.env (chmod 600) with everything the live launchers
# need.  Re-run this script any time a credential changes - it overwrites
# the file and scripts/live.sh picks it up automatically.  Secrets are
# entered hidden (no echo); blanks are allowed and only warn.
#
# Usage:  bash scripts/setup-live.sh
set -euo pipefail

SECRETS="${OX_SECRETS_FILE:-$HOME/.ox_secrets.env}"

echo "============================================================"
echo " OX-ALPHA live credentials setup"
echo " Writes: $SECRETS  (permissions 600)"
echo " Re-run any time a key changes - it just overwrites."
echo "============================================================"

read -rp "Dhan client ID [blank to skip]: " DHAN_CLIENT_ID
read -rsp "Dhan access token (hidden) [blank to skip]: " DHAN_TOKEN; echo
read -rp "Dhan whitelisted instance public IP, e.g. 13.207.244.242 [blank to skip]: " DHAN_STATIC_IP
read -rsp "Binance API key (hidden) [blank to skip]: " BINANCE_API_KEY; echo
read -rsp "Binance API secret (hidden) [blank to skip]: " BINANCE_API_SECRET; echo
read -rsp "Audit key, >= 32 chars (hidden) [blank = auto-generate]: " OX_AUDIT_KEY; echo

if [ -z "${OX_AUDIT_KEY:-}" ]; then
  OX_AUDIT_KEY="$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 48)"
fi

umask 077
cat > "$SECRETS" <<EOF
# OX-ALPHA live credentials - generated by scripts/setup-live.sh
# Permissions 600.  Never commit or share this file.
export OX_AUDIT_KEY='$OX_AUDIT_KEY'
export OX_LIVE_EXECUTION_APPROVED='YES_I_UNDERSTAND_LIVE_TRADING'
export DHAN_CLIENT_ID='${DHAN_CLIENT_ID:-}'
export DHAN_TOKEN='${DHAN_TOKEN:-}'
export DHAN_STATIC_IP='${DHAN_STATIC_IP:-}'
export BINANCE_API_KEY='${BINANCE_API_KEY:-}'
export BINANCE_API_SECRET='${BINANCE_API_SECRET:-}'
EOF
chmod 600 "$SECRETS"

if [ -n "${DHAN_CLIENT_ID:-}" ] && [ -n "${DHAN_TOKEN:-}" ]; then
  echo "Dhan credentials:    saved"
else
  echo "WARNING: Dhan credentials incomplete - 'live.sh dhan' / 'live.sh live-test' will refuse to start."
fi
if [ -n "${BINANCE_API_KEY:-}" ] && [ -n "${BINANCE_API_SECRET:-}" ]; then
  echo "Binance credentials: saved"
else
  echo "WARNING: Binance credentials incomplete - 'live.sh binance' will refuse to start."
fi

echo
echo "Next steps:"
echo "  bash scripts/live.sh live-test   # Dhan connectivity + credential check (safe)"
echo "  bash scripts/live.sh dhan        # NSE intraday agent, live Dhan"
echo "  bash scripts/live.sh binance     # promax multi-agent: Dhan equity + Binance spot/perp"
echo "  bash scripts/live.sh paper       # back to paper"